[ WARNING ] Directory `/local/scratch/hcui25/Project/xin/CS/GAN/CGAN_CIFAR/runs` already exists!
[ WARNING ] Directory `/local/scratch/hcui25/Project/xin/CS/GAN/CGAN_CIFAR/model/weights_gen0` already exists!
[ INFO ] TrainingEngine:
[ WARNING ] You have chosen a specific GPU. This will completely disable data parallelism.
[ INFO ] Creating model `cgan`.
Traceback (most recent call last):
  File "/local/scratch/hcui25/Project/xin/CS/GAN/CGAN_CIFAR/train.py", line 321, in <module>
    main(args)
  File "/local/scratch/hcui25/Project/xin/CS/GAN/CGAN_CIFAR/train.py", line 78, in main
    main_worker(ngpus_per_node, args)
  File "/local/scratch/hcui25/Project/xin/CS/GAN/CGAN_CIFAR/train.py", line 205, in main_worker
    fake_output = discriminator(fake, conditional)
  File "/home/hcui25/anaconda3/envs/llava-med/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hcui25/anaconda3/envs/llava-med/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/local/scratch/hcui25/Project/xin/CS/GAN/CGAN_CIFAR/cgan_pytorch/models/discriminator.py", line 60, in forward
    out = self.main(conditional_inputs)
  File "/home/hcui25/anaconda3/envs/llava-med/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hcui25/anaconda3/envs/llava-med/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hcui25/anaconda3/envs/llava-med/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/hcui25/anaconda3/envs/llava-med/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hcui25/anaconda3/envs/llava-med/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hcui25/anaconda3/envs/llava-med/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (64x21 and 3092x512)
